// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "../app/css/globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import { type Metadata } from 'next'

import { RootLayout } from '../app/components/RootLayout'

// import '../app/css/tailwind.css'
import "../app/css/globals.css";
export const metadata: Metadata = {
  title: {
    template: 'Crown',
    default: 'Crown Allstar',
  },
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full bg-neutral-950 text-base antialiased">
      <body className="flex min-h-full flex-col">
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  )
}
