import type { Metadata } from "next";
import { Header } from "./Header";
import HomePlayer from "./HomePlayer";
import "../css/globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomePage() {
  return (
    <div lang="en">
      <div className="flex flex-col h-screen w-screen">
        {/* <Header/> */}
        <HomePlayer/>
      </div>
    </div>
  );
}
